### ISSUE TITLE
Проблемы с локализацией

### ISSUE THREAD

**Issue by Ahaenor** [Teplitsa/Leyka#129]
Вопрос, заданный @FunkyXL:

> Как мы можем самостоятельно перевести в существующей форме следующие строки: ?
> 1. Изменить "or" на "или".
> 2. Перевести "MONTHLY DONATIONS" на "Ежемесячное пожертвование".
> Скрин: http://c2n.me/3DZkOZb
> 
> В каком файле это можно поправить? Проверил файл - \leyka\lang\leyka-ru_RU.po но там не оказалось нужной информации.

Спасибо за обращение. В ближайшей новой версии эти проблемы будут исправлены.
До этого вы можете исправить ошибки самостоятельно. Для этого:

**1.** Установите на сайте плагин [Loco Translate](https://wordpress.org/plugins/loco-translate/).
Активируйте его.

**2.** Перейдите в раздел Loco Translate -> Plugins -> Leyka.

**3.** Вы увидите 2 варианта русских перевода плагина. **Вам нужно удалить (Delete)** тот вариант, который находится в файле **languages/plugins/leyka-ru_RU.po**. Обычно это второй (нижний) вариант из двух.

**4.** После этого выберите скопировать (Copy) оставшийся вариант перевода. Откроется страница с настройками копирования. Укажите следующие настройки:
 - Choose a language: **Russian**.
 - Choose a location: **languages/plugins/leyka-<locale>.po**.
 - Template options: **Copy target translations from "ru_RU"**.

Выбрав такие настройки, нажмите **"Start translating"**.

Если всё было указано правильно, все строки на форме пожертвования станут русскими.

Приносим извинения за неудобства)

**Comment by FunkyXL** [comment]
Спасибо большое! Good job!03.11.2016, 14:46, "Lev Zvyagintsev" <notifications@github.com>:Вопрос, заданный @FunkyXL:

Как мы можем самостоятельно перевести в существующей форме следующие строки: ?

Изменить "or" на "или".
Перевести "MONTHLY DONATIONS" на "Ежемесячное пожертвование".
Скрин: http://c2n.me/3DZkOZb

В каком файле это можно поправить? Проверил файл - \leyka\lang\leyka-ru_RU.po но там не оказалось нужной информации.

Спасибо за обращение. В ближайшей новой версии эти проблемы будут исправлены.
До этого вы можете исправить ошибки самостоятельно. Для этого:
1. Установите на сайте плагин Loco Translate.
Активируйте его.
2. Перейдите в раздел Loco Translate -> Plugins -> Leyka.
3. Вы увидите 2 варианта русских перевода плагина. Вам нужно удалить (Delete) тот вариант, который находится в файле languages/plugins/leyka-ru_RU.po. Обычно это второй (нижний) вариант из двух.
4. После этого выберите скопировать (Copy) оставшийся вариант перевода. Откроется страница с настройками копирования. Укажите следующие настройки:

Choose a language: Russian.
Choose a location: languages/plugins/leyka-<locale>.po.
Template options: Copy target translations from "ru_RU".

Выбрав такие настройки, нажмите "Start translating".
Если всё было указано правильно, все строки на форме пожертвования станут русскими.
Приносим извинения за неудобства)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-------------------------------------------------- С уважением, АлексейE-mail: funkyxl@ya.ru

**Comment by Ahaenor** [comment]
Мы рады быть вам полезны)
